#!/usr/bin/env python3
"""
generate_cases.py – build deterministic toy ZIP archive test cases.

All archives are tiny, fake, generated by Python stdlib zipfile only.
No external archives, no network, no real files.
"""
import json
import zipfile
import io
import os
import struct
from pathlib import Path, PurePosixPath, PureWindowsPath

SEED = 42
CASES_FILE = "cases.json"
ARCHIVES_DIR = "archives"

os.makedirs(ARCHIVES_DIR, exist_ok=True)

cases = []


def write_zip(case_id, members, **meta):
    """members: list of (name, bytes, compress_type)"""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, data, ctype in members:
            zinfo = zipfile.ZipInfo(name)
            zinfo.compress_type = ctype
            zf.writestr(zinfo, data)
    archive_bytes = buf.getvalue()
    path = os.path.join(ARCHIVES_DIR, f"{case_id}.zip")
    with open(path, "wb") as f:
        f.write(archive_bytes)
    return archive_bytes, path


def write_zip_raw(case_id, archive_bytes):
    path = os.path.join(ARCHIVES_DIR, f"{case_id}.zip")
    with open(path, "wb") as f:
        f.write(archive_bytes)
    return path


def add_case(case_id, category, archive_bytes, archive_path,
             expected_member_names, expected_file_count,
             expected_uncompressed_size,
             expected_compression_methods=None,
             expected_crc_ok=True,
             expected_duplicate_names=False,
             expected_unsafe_path=False,
             expected_compression_ratio_guard=False,
             expected_safe_extract=True,
             case_tags=None,
             safe_to_extract_in_tempdir=True,
             dry_run_only=False,
             malformed=False,
             notes=""):
    cases.append({
        "case_id": case_id,
        "category": category,
        "archive_path": archive_path,
        "archive_byte_length": len(archive_bytes),
        "expected_member_names": expected_member_names,
        "expected_file_count": expected_file_count,
        "expected_uncompressed_size": expected_uncompressed_size,
        "expected_compression_methods": expected_compression_methods or [],
        "expected_crc_ok": expected_crc_ok,
        "expected_duplicate_names": expected_duplicate_names,
        "expected_unsafe_path": expected_unsafe_path,
        "expected_compression_ratio_guard": expected_compression_ratio_guard,
        "expected_safe_extract": expected_safe_extract,
        "case_tags": case_tags or [category],
        "safe_to_extract_in_tempdir": safe_to_extract_in_tempdir,
        "dry_run_only": dry_run_only,
        "malformed": malformed,
        "notes": notes,
    })


# --- Normal / directory cases --------------------------------------------

# C01 normal
ab, ap = write_zip("c01_normal", [("hello.txt", b"hi\n", zipfile.ZIP_DEFLATED)])
add_case("c01_normal", "normal", ab, ap, ["hello.txt"], 1, 3,
         expected_compression_methods=["deflated"],
         case_tags=["normal"])

# C02 nested dirs
ab, ap = write_zip("c02_nested", [
    ("a/b/c/nested.txt", b"nested\n", zipfile.ZIP_DEFLATED)])
add_case("c02_nested", "directory", ab, ap, ["a/b/c/nested.txt"], 1, 7,
         case_tags=["directory", "normal"])

# C03 empty dir entry
ab, ap = write_zip("c03_empty_dir", [("emptydir/", b"", zipfile.ZIP_STORED)])
add_case("c03_empty_dir", "directory", ab, ap, ["emptydir/"], 1, 0,
         expected_compression_methods=["stored"],
         case_tags=["directory", "empty_dir"])

# C04 multiple small files
ab, ap = write_zip("c04_multi", [
    (f"file{i}.txt", f"data{i}".encode(), zipfile.ZIP_DEFLATED) for i in range(5)])
add_case("c04_multi", "normal", ab, ap,
         [f"file{i}.txt" for i in range(5)], 5, sum(len(f"data{i}") for i in range(5)),
         case_tags=["normal", "multi"])

# --- Compression ----------------------------------------------------------

# C05 stored
ab, ap = write_zip("c05_stored", [("plain.txt", b"stored data", zipfile.ZIP_STORED)])
add_case("c05_stored", "compression", ab, ap, ["plain.txt"], 1, 11,
         expected_compression_methods=["stored"],
         case_tags=["compression", "stored"])

# C06 deflated
ab, ap = write_zip("c06_deflated", [("comp.txt", b"aaaaabbbbbccccc"*10, zipfile.ZIP_DEFLATED)])
add_case("c06_deflated", "compression", ab, ap, ["comp.txt"], 1, 150,
         expected_compression_methods=["deflated"],
         case_tags=["compression", "deflated"])

# C07 archive comment
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    zf.comment = b"archive comment here"
    zf.writestr("x.txt", b"y")
ab = buf.getvalue()
ap = write_zip_raw("c07_archive_comment", ab)
add_case("c07_archive_comment", "compression", ab, ap, ["x.txt"], 1, 1,
         case_tags=["compression", "archive_comment"],
         notes="archive comment present")

# C08 file comment – skipped (stdlib doesn't easily set file comments portably)

# --- Unicode / names ------------------------------------------------------

# C09 unicode filename
ab, ap = write_zip("c09_unicode", [("naïve_café_日本語.txt", b"unicode", zipfile.ZIP_DEFLATED)])
add_case("c09_unicode", "unicode_name", ab, ap, ["naïve_café_日本語.txt"], 1, 7,
         case_tags=["unicode_name"])

# C10 spaces/punctuation
ab, ap = write_zip("c10_spaces", [("my file (1) [final]!.txt", b"sp", zipfile.ZIP_DEFLATED)])
add_case("c10_spaces", "unicode_name", ab, ap, ["my file (1) [final]!.txt"], 1, 2,
         case_tags=["unicode_name", "spaces"])

# C11 backslash in name (NOT a separator in ZIP, it's a literal backslash)
ab, ap = write_zip("c11_backslash", [("folder\\file.txt", b"bs", zipfile.ZIP_DEFLATED)])
add_case("c11_backslash", "path_separator", ab, ap, ["folder\\file.txt"], 1, 2,
         expected_unsafe_path=True,  # conservative: backslash in ZIP names is risky cross-platform
         expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["path_separator", "windows_path"],
         notes="backslash is literal in ZIP spec, path separator on Windows – conservative validator rejects")

# C12 forward slash (normal)
ab, ap = write_zip("c12_fwdslash", [("folder/file.txt", b"ok", zipfile.ZIP_DEFLATED)])
add_case("c12_fwdslash", "path_separator", ab, ap, ["folder/file.txt"], 1, 2,
         case_tags=["path_separator", "normal"])

# --- Path traversal -------------------------------------------------------

# C13 leading slash absolute
ab, ap = write_zip("c13_abs", [("/etc/passwd", b"no", zipfile.ZIP_DEFLATED)])
add_case("c13_abs", "absolute_path", ab, ap, ["/etc/passwd"], 1, 2,
         expected_unsafe_path=True, expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["absolute_path", "traversal", "naive_negative"])

# C14 ../ traversal
ab, ap = write_zip("c14_dotdot", [("../evil.txt", b"no", zipfile.ZIP_DEFLATED)])
add_case("c14_dotdot", "traversal", ab, ap, ["../evil.txt"], 1, 2,
         expected_unsafe_path=True, expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["traversal", "naive_negative"])

# C15 nested ../../
ab, ap = write_zip("c15_dotdot2", [("../../escape.txt", b"x", zipfile.ZIP_DEFLATED)])
add_case("c15_dotdot2", "traversal", ab, ap, ["../../escape.txt"], 1, 1,
         expected_unsafe_path=True, expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["traversal", "naive_negative"])

# C16 Windows drive path
ab, ap = write_zip("c16_win_drive", [("C:/temp/file.txt", b"x", zipfile.ZIP_DEFLATED)])
add_case("c16_win_drive", "windows_path", ab, ap, ["C:/temp/file.txt"], 1, 1,
         expected_unsafe_path=True, expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["windows_path", "absolute_path", "naive_negative"],
         notes="drive-letter looks absolute")

# C17 Windows backslash traversal-looking
ab, ap = write_zip("c17_win_bs_traversal", [("..\\evil.txt", b"x", zipfile.ZIP_DEFLATED)])
add_case("c17_win_bs_traversal", "windows_path", ab, ap, ["..\\evil.txt"], 1, 1,
         expected_unsafe_path=True,
         expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["windows_path", "traversal"],
         notes="backslash traversal – literal on POSIX, risky on Windows")

# --- Duplicate names ------------------------------------------------------

# C18 duplicate filenames, different contents
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    zf.writestr("dup.txt", b"first")
    zf.writestr("dup.txt", b"second")
ab = buf.getvalue()
ap = write_zip_raw("c18_duplicate", ab)
# zipfile.infolist will see BOTH entries
add_case("c18_duplicate", "duplicate_name", ab, ap,
         ["dup.txt", "dup.txt"], 2, 11,  # 5+6
         expected_duplicate_names=True,
         case_tags=["duplicate_name", "naive_negative"],
         notes="two entries with same name, different content")

# C19 same file repeated 3x
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    for c in [b"a", b"b", b"c"]:
        zf.writestr("repeat.txt", c)
ab = buf.getvalue()
ap = write_zip_raw("c19_duplicate3", ab)
add_case("c19_duplicate3", "duplicate_name", ab, ap,
         ["repeat.txt", "repeat.txt", "repeat.txt"], 3, 3,
         expected_duplicate_names=True,
         case_tags=["duplicate_name"])

# --- CRC / malformed ------------------------------------------------------

# C20 CRC mismatch – corrupt the file data after writing
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    zf.writestr("good.txt", b"original data here")
ab = bytearray(buf.getvalue())
# Corrupt a byte in the compressed data (rough guess – find 'original')
try:
    idx = ab.find(b"original")
    if idx >= 0:
        ab[idx] ^= 0xFF
except Exception:
    pass
ab = bytes(ab)
ap = write_zip_raw("c20_crc_mismatch", ab)
add_case("c20_crc_mismatch", "crc_error", ab, ap, ["good.txt"], 1, 18,
         expected_crc_ok=False,
         expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["crc_error", "naive_negative"],
         notes="CRC should fail on read")

# C21 malformed non-ZIP
ab = b"This is definitely not a ZIP file.\x00\x01\x02"
ap = write_zip_raw("c21_malformed", ab)
add_case("c21_malformed", "malformed_zip", ab, ap, [], 0, 0,
         expected_crc_ok=False, expected_safe_extract=False,
         safe_to_extract_in_tempdir=False, malformed=True,
         case_tags=["malformed_zip", "naive_negative"])

# --- Prefix / suffix ------------------------------------------------------

# C22 prefix bytes before ZIP
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    zf.writestr("inner.txt", b"hi")
inner = buf.getvalue()
ab = b"PREFIX_JUNK_12345" + inner
ap = write_zip_raw("c22_prefix", ab)
add_case("c22_prefix", "prefix_suffix", ab, ap, ["inner.txt"], 1, 2,
         case_tags=["prefix_suffix"],
         notes="zipfile.ZipFile accepts prefix bytes")

# C23 suffix junk after ZIP
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    zf.writestr("inner.txt", b"hi")
inner = buf.getvalue()
ab = inner + b"_SUFFIX_JUNK_TAIL"
ap = write_zip_raw("c23_suffix", ab)
add_case("c23_suffix", "prefix_suffix", ab, ap, ["inner.txt"], 1, 2,
         case_tags=["prefix_suffix"])

# C24 concatenated ZIPs
buf1 = io.BytesIO()
with zipfile.ZipFile(buf1, "w") as zf:
    zf.writestr("a.txt", b"A")
buf2 = io.BytesIO()
with zipfile.ZipFile(buf2, "w") as zf:
    zf.writestr("b.txt", b"B")
ab = buf1.getvalue() + buf2.getvalue()
ap = write_zip_raw("c24_concat", ab)
# zipfile reads the second/last archive (EOCD search from end)
add_case("c24_concat", "prefix_suffix", ab, ap, ["b.txt"], 1, 1,
         case_tags=["prefix_suffix"],
         notes="concatenated ZIPs – zipfile finds EOCD from end, reads second archive")

# --- Zip bomb caveat (tiny!) ----------------------------------------------

# C25 tiny high-compression-ratio
# 50 KB of zeros compresses to ~70 bytes
bomb_data = b"\x00" * 50000
ab, ap = write_zip("c25_bomb_caveat", [("zeros.bin", bomb_data, zipfile.ZIP_DEFLATED)])
ratio = 50000 / len(ab) if len(ab) else 0
add_case("c25_bomb_caveat", "zip_bomb_caveat", ab, ap, ["zeros.bin"], 1, 50000,
         expected_compression_ratio_guard=True,
         case_tags=["zip_bomb_caveat"],
         notes=f"compression ratio ~{ratio:.1f}:1 – toy bomb caveat")

# C26 size guard – many small files count guard
members = [(f"f{i}.txt", b"x", zipfile.ZIP_DEFLATED) for i in range(40)]
ab, ap = write_zip("c26_many_files", members)
add_case("c26_many_files", "zip_bomb_caveat", ab, ap,
         [f"f{i}.txt" for i in range(40)], 40, 40,
         case_tags=["zip_bomb_caveat"],
         notes="40 files – triggers count guard in toy thresholds")

# C27 total uncompressed size guard
bigish = b"X" * 80000
ab, ap = write_zip("c27_big_uncomp", [("big.bin", bigish, zipfile.ZIP_STORED)])
add_case("c27_big_uncomp", "zip_bomb_caveat", ab, ap, ["big.bin"], 1, 80000,
         expected_compression_ratio_guard=False,
         case_tags=["zip_bomb_caveat"],
         notes="80KB uncompressed, stored – triggers size guard")

# --- Misc caveats ---------------------------------------------------------

# C28 unsupported compression method
# Create a normal zip then patch compression method to 99
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    zf.writestr("x.txt", b"hi")
ab = bytearray(buf.getvalue())
# Find local file header signature 0x04034b50, compression method is 2 bytes at offset 8
try:
    sig = b"\x50\x4b\x03\x04"
    idx = ab.find(sig)
    if idx >= 0:
        # compression method at idx+8
        ab[idx+8] = 99
        ab[idx+9] = 0
except Exception:
    pass
ab = bytes(ab)
ap = write_zip_raw("c28_unsupported_comp", ab)
# Note: Python zipfile still reads this fine in practice – patching only LFH not CDH
add_case("c28_unsupported_comp", "compression", ab, ap, ["x.txt"], 1, 2,
         expected_crc_ok=True,
         case_tags=["compression"],
         notes="patched compression method = 99 in LFH only – zipfile still reads OK, CDH has correct method")

# C29 symlink-like external_attr (Unix symlink flag 0xA000)
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    zi = zipfile.ZipInfo("link.txt")
    zi.external_attr = 0xA1FF0000  # symlink-ish
    zf.writestr(zi, b"target")
ab = buf.getvalue()
ap = write_zip_raw("c29_symlink_attr", ab)
add_case("c29_symlink_attr", "symlink_caveat", ab, ap, ["link.txt"], 1, 6,
         case_tags=["symlink_caveat"],
         notes="external_attr looks like symlink – never follow")

# C30 executable-looking
ab, ap = write_zip("c30_executable", [("runme.exe", b"MZfake", zipfile.ZIP_DEFLATED)])
add_case("c30_executable", "extension_caveat", ab, ap, ["runme.exe"], 1, 6,
         case_tags=["extension_caveat"],
         notes="executable-looking filename")

# C31 misleading extension: invoice.pdf.zip as a member name? no – archive named misleadingly
# Instead: member named "invoice.pdf" that is actually a zip, and archive named invoice.pdf.zip
# Simpler: member named "invoice.pdf" with innocent content – extension trust baseline should fail to catch real risk
ab, ap = write_zip("c31_ext_trust", [("invoice.pdf", b"not a pdf", zipfile.ZIP_DEFLATED)])
add_case("c31_ext_trust", "extension_caveat", ab, ap, ["invoice.pdf"], 1, 9,
         case_tags=["extension_caveat", "naive_negative"],
         notes="extension says pdf, content is plain text – trust is a caveat")

# C32 double extension
ab, ap = write_zip("c32_double_ext", [("document.txt.exe", b"x", zipfile.ZIP_DEFLATED)])
add_case("c32_double_ext", "extension_caveat", ab, ap, ["document.txt.exe"], 1, 1,
         case_tags=["extension_caveat", "naive_negative"])

# C33 archive named misleadingly – we can't rename the archive file meaningfully in-case, skip, use member trick
# already covered

# C34 normal again for balance
ab, ap = write_zip("c34_normal2", [("readme.md", b"# hi\n", zipfile.ZIP_DEFLATED)])
add_case("c34_normal2", "normal", ab, ap, ["readme.md"], 1, 5,
         case_tags=["normal"])

# C35 safe subdir
ab, ap = write_zip("c35_safe_subdir", [("safe/sub/file.txt", b"ok", zipfile.ZIP_DEFLATED)])
add_case("c35_safe_subdir", "directory", ab, ap, ["safe/sub/file.txt"], 1, 2,
         case_tags=["directory", "normal"])

# C36 path with ./
ab, ap = write_zip("c36_dot_slash", [("./file.txt", b"x", zipfile.ZIP_DEFLATED)])
add_case("c36_dot_slash", "path_separator", ab, ap, ["./file.txt"], 1, 1,
         expected_unsafe_path=False,  # ./ is safe, normalizes to file.txt
         case_tags=["path_separator"],
         notes="./ prefix – should normalize safely")

# C37 path with a//b (double slash)
ab, ap = write_zip("c37_double_slash", [("a//b.txt", b"x", zipfile.ZIP_DEFLATED)])
add_case("c37_double_slash", "path_separator", ab, ap, ["a//b.txt"], 1, 1,
         case_tags=["path_separator"])

# C38 trailing slash dir + file
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as zf:
    zf.writestr("dir/", b"")
    zf.writestr("dir/file.txt", b"y")
ab = buf.getvalue()
ap = write_zip_raw("c38_dir_plus_file", ab)
add_case("c38_dir_plus_file", "directory", ab, ap, ["dir/", "dir/file.txt"], 2, 1,
         case_tags=["directory"])

# C39 hidden dotfile
ab, ap = write_zip("c39_dotfile", [(".hidden", b"s", zipfile.ZIP_DEFLATED)])
add_case("c39_dotfile", "normal", ab, ap, [".hidden"], 1, 1,
         case_tags=["normal"])

# C40 empty file
ab, ap = write_zip("c40_empty_file", [("empty.txt", b"", zipfile.ZIP_STORED)])
add_case("c40_empty_file", "normal", ab, ap, ["empty.txt"], 1, 0,
         expected_compression_methods=["stored"],
         case_tags=["normal"])

# C41 traversal with mixed separators
ab, ap = write_zip("c41_mixed_sep", [("a/../../b.txt", b"x", zipfile.ZIP_DEFLATED)])
add_case("c41_mixed_sep", "traversal", ab, ap, ["a/../../b.txt"], 1, 1,
         expected_unsafe_path=True, expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["traversal", "naive_negative"])

# C42 absolute Windows backslash
ab, ap = write_zip("c42_win_abs_bs", [("\\windows\\system32\\x", b"x", zipfile.ZIP_DEFLATED)])
add_case("c42_win_abs_bs", "windows_path", ab, ap, ["\\windows\\system32\\x"], 1, 1,
         expected_unsafe_path=True,
         expected_safe_extract=False,
         safe_to_extract_in_tempdir=False,
         case_tags=["windows_path"],
         notes="leading backslash – absolute on Windows")

print(f"Generated {len(cases)} cases in {ARCHIVES_DIR}/")
with open(CASES_FILE, "w") as f:
    json.dump(cases, f, indent=2)
print(f"Wrote {CASES_FILE}")
